name: CI
on: [push, pull_request]

jobs:
  test-example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable

    steps:
      - uses: actions/checkout@v4
        with:
          path: types-wasm-go-plugin

      - run: cp types-wasm-go-plugin/go.sum . # Needed to get setup-go to work

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version: '1.21.7'